version: '3'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://roberto-es-cluster-01:9200
    networks:
      - roberto-es-cluster
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: kibana
    environment:
      - TIMELION_ENABLED=true
      - ELASTICSEARCH_USERNAME="elastic"
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH_URL=http://roberto-es-cluster-01:9200
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES="$CERTS_DIR/ca/ca.crt"
    ports:
      - "5601:5601"
    volumes:
      - ./certs:$CERTS_DIR
    networks:
      - roberto-es-cluster
  roberto-es-cluster-01:
    image: 201210704116/elasticsearch
    container_name: roberto-es-cluster-01
    environment:
      - cluster.name=roberto-es-cluster
      - node.name=roberto-es-cluster-01
      - node.master=true
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      # 是否启用权限认证
      - xpack.security.enabled=$SECURITY_ENABLED      
      
      # - xpack.security.http.ssl.enabled=true
      # - xpack.security.http.ssl.verification_mode=certificate
      # - xpack.security.http.ssl.key=$CERTS_DIR/roberto-es-cluster-01/roberto-es-cluster-01.key
      # - xpack.security.http.ssl.certificate=$CERTS_DIR/roberto-es-cluster-01/roberto-es-cluster-01.crt
      # - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt

      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.ssl.certificate=$CERTS_DIR/roberto-es-cluster-01/roberto-es-cluster-01.crt
      - xpack.ssl.key=$CERTS_DIR/roberto-es-cluster-01/roberto-es-cluster-01.key
      
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      # - "discovery.zen.minimum_master_nodes=2"
      # - "discovery.zen.ping.unicast.hosts=roberto-es-cluster-02,roberto-es-cluster-03"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - ./certs:$CERTS_DIR
      - roberto-es-cluster-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - roberto-es-cluster
volumes:
  roberto-es-cluster-01:
    driver: local
networks:
  roberto-es-cluster:
    driver: bridge
